services:
  - type: web
    name: music-mix
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 deploy/app_minimal.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
